# Generated by Django 3.0.6 on 2020-05-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('short_bio', models.TextField()),
                ('picture', models.ImageField(upload_to='veterinarians/', verbose_name='Profile Picture')),
                ('facebook', models.URLField(default='https://www.google.com/', verbose_name='Facebook Profile')),
                ('twitter', models.URLField(default='https://www.google.com/', verbose_name='Twitter Profile')),
                ('google', models.URLField(default='https://www.google.com/', verbose_name='Google Plus')),
                ('instagram', models.URLField(default='https://www.google.com/', verbose_name='Instagram Profile')),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
            },
        ),
    ]
